### PR TITLE
PHP 8.4 Compatibility fixes

### PR DESCRIPTION
**Pull request by isehrob-stripe**
### Context

Attempt to release a new v4.0.0 (https://github.com/taxjar/taxjar-magento2-extension/pull/386) failed because I missed a critical fact that magento 2.4.8 requires php8.4 not php8.3. V4.0.0 was tested extensively with php8.3 which is why I missed many incompatibility issues with php8.4. This PR fixes all of them.

### Description

phpcs errors:
Below the errors we got from tech review for additional context. There were 4 linter errors and many DI complication failures. I've run into them when I upgraded the php version to 8.4.

image

DI compilation errors:
image

All of them are fixed in this PR and both automatic and manual tests are now green.

### Testing

`bin/phpcs app/code --report=summary` confirms that no more errors. Warnings are around doc strings, formatting etc which shouldn't be a cause for tech review failure.
image

Both integration and unit tests are green.
image

Manual tests passed: Tax calculations, Address validation, Transaction sync, Date filtering all work as expected.
image

#### Versions

- [x] Magento 2.4.8

- [x] Magento Open Source (formerly Magento 2 Community Edition)
- [ ] Adobe Commerce (formerly Magento 2 Enterprise Edition)

- [x] PHP 8.4

### CODE REVIEW

File: Plugin/RequireJs/AfterFiles.php
Comment (saville-stripe) [inline Plugin/RequireJs/AfterFiles.php:1]: These leading `?` on the type are about Optional/Maybe?

Comment (saville-stripe) [reply Plugin/RequireJs/AfterFiles.php:1]: Ah "nullable type"

**Review by saville-stripe — APPROVED** [review]
Based on a code read-through, I believe this all makes sense.

**Review by smolentzov-stripe — APPROVED** [review]
This looks good to me based on code review and your click-testing!
